print("Hello world")
print("This is a test of the Agentic app.")
print("Agentic is a powerful tool for building intelligent agents.")
print("With Agentic, you can create agents that can learn, adapt, and interact with their environment.")
print("Agentic is designed to be easy to use and flexible, allowing you to create agents for a wide range of applications.")